### ISSUE TITLE
Add .svn, .git and .hg folders to exlude list.

### ISSUE THREAD

**Issue by jezdez** [ella/setuptools-dummy#1]
It makes no sense to include the version data in the source distribution.

**Comment by ella** [comment]
i hope: ^.[^/]+
does the trick :))

EXCLUDE = re.compile(r'(^build|^.[^/]+|[^/]+.egg-info|.*.py[co]$)')

**Comment by ella** [comment]
okay, it does

**Comment by jezdez** [comment]
Indeed, that was as an error on my part, nevermind :)
